### PR TITLE
Watercolor layer

### PR DESCRIPTION
**Pull request by pmgouveia**

### CODE REVIEW

**Comment by cdauth** [comment]
Hey,

thanks a lot for your contribution.

I also came across this layer when thinking about which layers to include. In the end I decided not to include it because I felt like it was not generically useful enough.

Can you think of a case that applies to a lot of people where this particular layer would be useful? Or you think it is only useful in some special cases?

I tend more to making the list of layers configurable for collaborative maps rather than adding new layers to the default list.

**Comment by pmgouveia** [comment]
aw right.. i agree with you.. there are thousands of layers out there in the internet..! I tought about moving this to a file... or as you said the user could customize when creating a new pad!

**Comment by cdauth** [comment]
Can you explain what you mean by moving this to a file?

**Comment by pmgouveia** [comment]
I didn't had time.. ill close this pull request.. for now.

**Pull request closed without merging**
